### ISSUE TITLE
index.css Styling not correctly displaying.

### ISSUE THREAD

**Issue by FrenzyNwoba** [bradtraversy/react-crash-2021#8]
After copying your styling into index.css , The tiny blue border did not show up, the margin still hanging left.

But the font did change.

Probably there's a reason for all of that.

![Screenshot - 06_04_2021 , 9_36_14 AM](https://user-images.githubusercontent.com/64613243/113683407-10837200-96bc-11eb-9e7a-10205691c178.png)

**Comment by DanishShafi** [comment]
Yes, I also faced the same problem.

**Comment by FrenzyNwoba** [comment]
**PROBLEM SOLVED**

Add the below CSS Styling to your **index.css** file

`  
body {
  font-family: 'Poppins', sans-serif;
  border: 5px solid green;
  border-radius: 20px;
}
`

**Comment by ajaxStardust** [comment]
> After copying your styling into index.css

I have an issue with index.css as well, but no errors. I simply don't understand where the CSS is supposed to be copied from prior to pasting it into index.css at approximately 32:30 on the timeline of "React JS Crash Course".
Mr Traversy states it can be found at GitHub in the repository description. Clearly, I'm confused as I don't see anyone else having addressed this.

**Comment by ajaxStardust** [comment]
found the code:
https://github.com/bradtraversy/react-crash-2021/blob/master/src/index.css
